# ===================================================================
# CONFIGURACIÓN DE RIFLE (Apertura de archivos)
# ===================================================================

# 1. Archivos de texto y código -> Siempre con Neovim
mime ^text,  label editor = nvim -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|sh|lua|conf = nvim -- "$@"

# 2. Archivos de Audio y Video -> Con MPV
mime ^audio|^video, has mpv = mpv -- "$@"

# 3. Imágenes y PDFs -> Con el visor por defecto de tu sistema
mime ^image, has xdg-open = xdg-open "$@"
ext pdf, has xdg-open = xdg-open "$@"

# 4. Cualquier otra cosa -> Que el sistema decida con xdg-open
has xdg-open = xdg-open "$@"
